
# 目标名字
target = "base_test"
mode = ""
source_type = "excel"

sources = [
    { file_name = "base_test.xlsx",    sheet_name = "Sheet1" },
]


fields = [
    { active = true,   sname = "id" ,      tname = "id" ,      type = "int" ,  		key = 1,    desc = "主id"},
    { active = true,   sname = "name" ,    tname = "name" ,    type = "string",  	key = 0,    desc = "名字"},
    { active = true,   sname = "age" ,     tname = "age" ,     type = "int" ,  		key = 0,    desc = "年龄"},
	{ active = true,   sname = "course" ,  tname = "course" ,  type = "[]int" ,  	key = 0,    desc = "学科"},
    { active = true,   sname = "big_data_id" ,      tname = "bigDataId" ,       type = "int" ,  	        key = 0,    desc = "对应big_data表id"},
    { active = true,   sname = "item_type" ,        tname = "itemType" ,        type = "ItemType" ,  	    key = 0,    desc = "道具类型，测试枚举1"},
    { active = true,   sname = "condition_type" ,   tname = "conditionType" ,  type = "ConditionType" ,  	key = 0,    desc = "条件类型，测试枚举2"},
    { active = true,   sname = "position",          tname = "position",     type = "PointInt",  	key = 0,    desc = "位置"},
    { active = true,   sname = "rewards",   tname = "rewards",  type = "KVList_IntInt",  	key = 0,    desc = "奖励"},
    { active = true,   sname = "vector3",   tname = "vector3",  type = "TestVector3",  	key = 0,    desc = "测试使用脚本自定义字段类型" }
]

# 数据检测示例，$代表一行数据，table代表当前表，global代表全局，global[name]可以取到其他表的数据,extra表示当前表的额外新增数据
# global为false表是一行行数据检测，会有$。如果通过&&放到一行配置中能提升运行效率
# global为true表示是这个表单次的检查
checks = [
    { active = true, global = false, code = """ $.age < 60 """ },
    { active = true, global = false, code = """ $.bigDataId == 0 || global["big_data"][$.bigDataId] != nil """ },
    { active = true, global = true, code = """ table[int32(4)].name =="李四" """ },
]
