target = "complex_test"
mode = ""
source_type= "excel"

sources = [
	{ file_name = "complex_test.xlsx",    sheet_name = "Sheet1" },
]

fields = [
	{ active = true,   sname = "key1" ,      tname = "key1" ,      type = "int" ,  key = 1,    desc = "id" },
	{ active = true,   sname = "key2" ,      tname = "key2" ,      type = "string" ,  key = 2,    desc = "id2" },
	{ active = true,   sname = "content" ,      tname = "content" ,      type = "string" ,  key = 0,    desc = "内容" },
	{ active = true,   sname = "number" ,      tname = "number" ,      type = "float" ,  key = 0,    desc = "数字" },
	{ active = true,   sname = "test_list" ,      tname = "test_list" ,      type = "[]int" ,  key = 0,    desc = "列表" },
	{ active = true,   sname = "test_map" ,      tname = "test_map" ,      type = "map[int]string" ,  key = 0,    desc = "字典" },
]
