# 所有的路径填相对exe执行文件的相对路径
# 全局的一些配置
# 处理excel的配置
[table]
# Excel策划配置表目录
src_dir = "./excels"
# 表格字段名行号
name = 0
# 表格描述行号
desc = 4
# 表格数据起始行号，由空号结束
data_start = 5
# 配置数组的分隔符
array_split = "_"
# 配置map的分隔符
map_split1 = "|"
map_split2 = "="

# 控制导表的元配置
[meta]
# 生成出来的表meta配置临时目录
gen_dir = "./temp_meta"

[meta.rule_lua]
config_dir = "./lua_meta"
temp_dir = "./temp_lua"

[meta.rule_json]
config_dir = "./json_meta"
output_dir = "./temp_output_json"

[meta.rule_cs_proto]
config_dir = "./cs_meta"
proto_temp_dir = "./temp_proto"
proto_cs_dir = "./temp_output_proto_cs"
bytes_dir = "./temp_output_cs_bytes"
protoc_win_dir = "./protoc.exe"
protoc_mac_dir = "./protoc"
