# 所有的路径填相对exe执行文件的相对路径
# 全局的一些配置
# 处理excel的配置
[table]
# Excel策划配置表目录
src_dir = "./excels"
# 表格字段名行号
name = 0
# 表格描述行号
desc = 4
# 表格数据起始行号，由空号结束
data_start = 5
# 配置数组的分隔符
array_split = "_"
# 配置map的分隔符
map_split1 = "|"
map_split2 = "="

# 控制导表的元配置
[meta]
# 生成出来的表meta配置临时目录
gen_dir = "./temp_meta"

[[meta.rules]]
rule_name = "json"
config_dir = "./json_meta"
    [meta.rules.json]
    json_out = "./output/json"

[[meta.rules]]
rule_name = "lua"
config_dir = "./lua_meta"
[meta.rules.lua]
    lua_out = "./output/lua"
    post_process = true     #导出配置的后处理开关
    temp_dir = "./temp_work/temp_lua"
    post_process_lua = "./tools/DataTableOptimizer.lua"
    post_work_dir = "./tools"
    lua_win_dir = "./tools/lua5.3/lua53.exe"
    lua_mac_dir = "./tools/lua5.3/lua53"

[[meta.rules]]
rule_name = "cs_proto"
config_dir = "./cs_proto_meta"
[meta.rules.cs_proto]
    proto_package = "table"
    proto_temp_dir = "./temp_work/temp_proto"
    proto_cs_dir = "./output/proto_cs"
    bytes_dir = "./output/proto_bytes"
    protoc_win_dir = "./tools/protoc.exe"
    protoc_mac_dir = "./tools/protoc"

[[meta.rules]]
rule_name = "cs_bin"
config_dir = "./cs_bin_config/table_meta"
[meta.rules.cs_bin]
    code_temp_dir = "./temp_work/temp_cs_bin_code"
    data_temp_dir = "./temp_work/temp_cs_bin_data"
    gen_code_dir = "./projects/proj_cs_bin/src/gen"
    data_bin_dir = "./projects/proj_cs_bin/table_bytes"
    code_namespace = "CfgTable"
    #toml支持多行文本
    gen_code_head = """using Serialization;
    """
    code_not_found_key = """#if UNITY_EDITOR
Debug.LogError($"[%s] config id not found,id:{%s}");
#endif"""
    # 以下是生成的优化相关数据
    gen_optimize = true
    # 枚举文件路径集，可以支持多个，以及*或**匹配
    enum_files = [
        "./cs_bin_config/enum_define/*.toml",
    ]
    # 枚举，统一添加一个的前缀名，可为空
    enum_define_prefix = ""
    # 自定义class，统一添加一个的前缀名，可为空
    class_define_prefix = ""
    # 添加内置代码的扩展类型支持
    builtin_field_types = [
        "PointInt",
        "KVList_IntInt",
        "KVList_IntFloat",
    ]


